-- =============================================
-- PART 1: AUCA SYSTEM ACCESS POLICY (TRIGGERS)
-- =============================================


CREATE TABLE system_access_audit (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(100) DEFAULT USER,
    attempt_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    attempted_action VARCHAR2(500),
    rejection_reason VARCHAR2(500)
);


CREATE TABLE employees (
    employee_id NUMBER PRIMARY KEY,
    salary NUMBER,
    employee_name VARCHAR2(100) 
);


INSERT INTO employees (employee_id, salary, employee_name) VALUES (101, 50000, 'John Doe');
INSERT INTO employees (employee_id, salary, employee_name) VALUES (102, 60000, 'Jane Smith');
COMMIT;


CREATE OR REPLACE TRIGGER enforce_system_access
    BEFORE INSERT OR UPDATE OR DELETE ON employees
DECLARE
    v_day VARCHAR2(20);
    v_time NUMBER;
    v_reason VARCHAR2(500);
    PRAGMA AUTONOMOUS_TRANSACTION; 
BEGIN
 
    v_day := TO_CHAR(SYSDATE, 'DY');
    v_time := TO_NUMBER(TO_CHAR(SYSDATE, 'HH24.MI'));

   
    IF v_day IN ('SAT', 'SUN') THEN
        v_reason := 'Attempted access on Sabbath (' || v_day || ')';
    ELSIF (v_time < 8.00 OR v_time >= 17.00) THEN
        v_reason := 'Attempted access outside business hours. Time: ' || TO_CHAR(SYSDATE, 'HH24:MI');
    END IF;

  
    IF v_reason IS NOT NULL THEN
        INSERT INTO system_access_audit (attempted_action, rejection_reason)
        VALUES (ORA_DICT_OBJ_NAME || ' Operation', v_reason);
       
        RAISE_APPLICATION_ERROR(-20001, 'System Access Denied. ' || v_reason);
    END IF;
END enforce_system_access;
/
