-- =============================================
-- PART 3: SUSPICIOUS LOGIN MONITORING (TRIGGERS)
-- =============================================


CREATE TABLE login_audit (
    audit_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(100) NOT NULL,
    attempt_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    status VARCHAR2(10) NOT NULL CHECK (status IN ('SUCCESS', 'FAILED')),
    ip_address VARCHAR2(45)
);


CREATE TABLE security_alerts (
    alert_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(100) NOT NULL,
    failed_attempts NUMBER NOT NULL,
    alert_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    alert_message VARCHAR2(500) NOT NULL,
    contact_email VARCHAR2(100)
);

CREATE OR REPLACE TRIGGER track_suspicious_logins
    FOR INSERT ON login_audit
    COMPOUND TRIGGER

    TYPE username_table_type IS TABLE OF NUMBER INDEX BY VARCHAR2(100);
    g_failed_counts username_table_type;

    BEFORE EACH ROW IS
    BEGIN
        IF :NEW.status = 'FAILED' THEN
            IF g_failed_counts.EXISTS(:NEW.username) THEN
                g_failed_counts(:NEW.username) := g_failed_counts(:NEW.username) + 1;
            ELSE
                g_failed_counts(:NEW.username) := 1;
            END IF;
        END IF;
    END BEFORE EACH ROW;

    AFTER STATEMENT IS
        v_username VARCHAR2(100);
        v_failed_count NUMBER;
    BEGIN
        v_username := g_failed_counts.FIRST;
        
        WHILE v_username IS NOT NULL LOOP
            IF g_failed_counts(v_username) >= 3 THEN
                SELECT COUNT(*)
                INTO v_failed_count
                FROM login_audit
                WHERE username = v_username
                  AND status = 'FAILED'
                  AND TRUNC(attempt_time) = TRUNC(SYSDATE);
                
                IF v_failed_count >= 3 THEN
                    INSERT INTO security_alerts (username, failed_attempts, alert_message, contact_email)
                    VALUES (
                        v_username,
                        v_failed_count,
                        'Suspicious login activity: ' || v_failed_count || ' failed attempts today.',
                        'security-team@auca.ac.nw'
                    );
                    COMMIT;
                END IF;
            END IF;
            v_username := g_failed_counts.NEXT(v_username);
        END LOOP;
        g_failed_counts.DELETE;
    END AFTER STATEMENT;
END track_suspicious_logins;
/


DECLARE
    v_login_count NUMBER;
    v_alert_count NUMBER;
BEGIN
    DBMS_OUTPUT.PUT_LINE('=== CREATING LOGIN MONITORING SAMPLE DATA ===');
    
    INSERT INTO login_audit (username, status, ip_address) VALUES ('john_doe', 'FAILED', '192.168.1.100');
    INSERT INTO login_audit (username, status, ip_address) VALUES ('john_doe', 'FAILED', '192.168.1.100');
    INSERT INTO login_audit (username, status, ip_address) VALUES ('john_doe', 'FAILED', '192.168.1.100');
    

    INSERT INTO login_audit (username, status, ip_address) VALUES ('jane_smith', 'SUCCESS', '192.168.1.101');
    
    INSERT INTO login_audit (username, status, ip_address) VALUES ('bob_wilson', 'FAILED', '192.168.1.102');
    INSERT INTO login_audit (username, status, ip_address) VALUES ('bob_wilson', 'FAILED', '192.168.1.102');
    
    INSERT INTO login_audit (username, status, ip_address) VALUES ('alice_brown', 'FAILED', '192.168.1.103');
    INSERT INTO login_audit (username, status, ip_address) VALUES ('alice_brown', 'FAILED', '192.168.1.103');
    INSERT INTO login_audit (username, status, ip_address) VALUES ('alice_brown', 'FAILED', '192.168.1.103');
    
    COMMIT;
    

    SELECT COUNT(*) INTO v_login_count FROM login_audit;
    SELECT COUNT(*) INTO v_alert_count FROM security_alerts;
    
    DBMS_OUTPUT.PUT_LINE('Login audit records created: ' || v_login_count);
    DBMS_OUTPUT.PUT_LINE('Security alerts generated: ' || v_alert_count);
    DBMS_OUTPUT.PUT_LINE('✓ Login monitoring sample data created successfully');
END;
/

