
-- =============================================
-- PART 4: HOSPITAL MANAGEMENT PACKAGE (BULK PROCESSING)
-- =============================================

-- Create hospital tables
CREATE TABLE patients (
    patient_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    age NUMBER,
    gender VARCHAR2(10),
    admitted VARCHAR2(3) DEFAULT 'NO' CHECK (admitted IN ('YES', 'NO'))
);

CREATE TABLE doctors (
    doctor_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    specialty VARCHAR2(100)
);

-- Hospital management package specification
CREATE OR REPLACE PACKAGE hospital_mgmt AS
    TYPE patient_rec_type IS RECORD (
        patient_id NUMBER,
        name VARCHAR2(100),
        age NUMBER,
        gender VARCHAR2(10),
        admitted VARCHAR2(3)
    );
    
    TYPE patient_tbl_type IS TABLE OF patient_rec_type;
    
    PROCEDURE bulk_load_patients(p_patient_list IN patient_tbl_type);
    FUNCTION show_all_patients RETURN SYS_REFCURSOR;
    FUNCTION count_admitted RETURN NUMBER;
    PROCEDURE admit_patient(p_patient_id IN NUMBER);
END hospital_mgmt;
/

-- Hospital management package body
CREATE OR REPLACE PACKAGE BODY hospital_mgmt IS
    PROCEDURE bulk_load_patients(p_patient_list IN patient_tbl_type) IS
    BEGIN
        FORALL i IN 1..p_patient_list.COUNT
            INSERT INTO patients (name, age, gender, admitted)
            VALUES (p_patient_list(i).name, p_patient_list(i).age, p_patient_list(i).gender, p_patient_list(i).admitted);
        
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Successfully loaded ' || SQL%ROWCOUNT || ' patients.');
    END bulk_load_patients;

    FUNCTION show_all_patients RETURN SYS_REFCURSOR IS
        patient_cursor SYS_REFCURSOR;
    BEGIN
        OPEN patient_cursor FOR 
            SELECT patient_id, name, age, gender, admitted 
            FROM patients 
            ORDER BY patient_id;
        RETURN patient_cursor;
    END show_all_patients;

    FUNCTION count_admitted RETURN NUMBER IS
        v_count NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_count FROM patients WHERE admitted = 'YES';
        RETURN v_count;
    END count_admitted;

    PROCEDURE admit_patient(p_patient_id IN NUMBER) IS
        v_patient_exists NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_patient_exists 
        FROM patients 
        WHERE patient_id = p_patient_id;
        
        IF v_patient_exists = 0 THEN
            RAISE_APPLICATION_ERROR(-20002, 'Patient with ID ' || p_patient_id || ' not found.');
        ELSE
            UPDATE patients SET admitted = 'YES' WHERE patient_id = p_patient_id;
            COMMIT;
            DBMS_OUTPUT.PUT_LINE('Patient ' || p_patient_id || ' has been admitted.');
        END IF;
    END admit_patient;
END hospital_mgmt;
/

-- Create sample data for hospital system
DECLARE
    patient_list hospital_mgmt.patient_tbl_type := hospital_mgmt.patient_tbl_type();
BEGIN
    DBMS_OUTPUT.PUT_LINE('=== CREATING HOSPITAL SAMPLE DATA ===');
    
    -- Insert sample doctors data
    INSERT INTO doctors (name, specialty) VALUES ('Dr. Michael Chen', 'Cardiology');
    INSERT INTO doctors (name, specialty) VALUES ('Dr. Sarah Johnson', 'Pediatrics');
    INSERT INTO doctors (name, specialty) VALUES ('Dr. Robert Brown', 'Surgery');
    INSERT INTO doctors (name, specialty) VALUES ('Dr. Emily Davis', 'Neurology');
    INSERT INTO doctors (name, specialty) VALUES ('Dr. James Wilson', 'Orthopedics');
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('✓ Sample doctors data inserted');

    -- Clear existing patients
    DELETE FROM patients;
    COMMIT;

    -- Initialize and populate patient collection
    patient_list.EXTEND(8);
    patient_list(1) := hospital_mgmt.patient_rec_type(NULL, 'Alice Smith', 30, 'F', 'NO');
    patient_list(2) := hospital_mgmt.patient_rec_type(NULL, 'Bob Johnson', 45, 'M', 'NO');
    patient_list(3) := hospital_mgmt.patient_rec_type(NULL, 'Carol Davis', 28, 'F', 'NO');
    patient_list(4) := hospital_mgmt.patient_rec_type(NULL, 'David Wilson', 65, 'M', 'YES');
    patient_list(5) := hospital_mgmt.patient_rec_type(NULL, 'Emma Thompson', 52, 'F', 'NO');
    patient_list(6) := hospital_mgmt.patient_rec_type(NULL, 'Frank Miller', 38, 'M', 'YES');
    patient_list(7) := hospital_mgmt.patient_rec_type(NULL, 'Grace Lee', 29, 'F', 'NO');
    patient_list(8) := hospital_mgmt.patient_rec_type(NULL, 'Henry Taylor', 71, 'M', 'YES');
    
    -- Bulk load patients
    hospital_mgmt.bulk_load_patients(patient_list);
END;
/

-- Test hospital management system
BEGIN
    DBMS_OUTPUT.PUT_LINE('=== HOSPITAL MANAGEMENT TEST ===');
    
    -- Show all patients
    DECLARE
        patient_cursor SYS_REFCURSOR;
        patient_rec patients%ROWTYPE;
        v_patient_count NUMBER := 0;
    BEGIN
        patient_cursor := hospital_mgmt.show_all_patients;
        DBMS_OUTPUT.PUT_LINE(CHR(10) || 'ALL PATIENTS:');
        LOOP
            FETCH patient_cursor INTO patient_rec;
            EXIT WHEN patient_cursor%NOTFOUND;
            v_patient_count := v_patient_count + 1;
            DBMS_OUTPUT.PUT_LINE('ID: ' || patient_rec.patient_id || ' - ' || 
                               patient_rec.name || ' (Admitted: ' || patient_rec.admitted || ')');
        END LOOP;
        CLOSE patient_cursor;
        DBMS_OUTPUT.PUT_LINE('Total patients: ' || v_patient_count);
    END;
    
    -- Test admission process
    DBMS_OUTPUT.PUT_LINE(CHR(10) || 'ADMISSION PROCESS:');
    DBMS_OUTPUT.PUT_LINE('Admitted patients before: ' || hospital_mgmt.count_admitted);
    hospital_mgmt.admit_patient(1);
    hospital_mgmt.admit_patient(3);
    DBMS_OUTPUT.PUT_LINE('Admitted patients after: ' || hospital_mgmt.count_admitted);
    
    -- Test error handling
    BEGIN
        hospital_mgmt.admit_patient(999);
    EXCEPTION
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('Expected error for non-existent patient: ' || SQLERRM);
    END;
END;
/
